shallow_clone: true

# turn of support for MS project build support (not needed)
build: off

environment:
  APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu2004

  matrix:
  - job_name: sshd
  - job_name: httpd

cache:
  - $(job_name).dockerimg.gz -> recipes/$(job_name)/Dockerfile, recipes/$(job_name)/id_rsa.pub

artifacts:
  - path: $(job_name).dockerimg.gz
    name: $(job_name) Docker image
    type: File

build_script:
  - echo ${APPVEYOR_JOB_NAME}
  - export DOCKER_CONTAINER_NAME="${APPVEYOR_JOB_NAME}"
  - export DOCKER_CONTAINER_SPECPATH="recipes/${APPVEYOR_JOB_NAME}"
  - export DOCKER_IMAGE_FILE="${APPVEYOR_JOB_NAME}.dockerimg.gz"
  # if there is no image cached already, build one, and write it out in
  # compressed from (to save on cache quota and network IO)
  - "[ ! -f \"${DOCKER_IMAGE_FILE}\" ] && ( docker build -t \"${DOCKER_CONTAINER_NAME}\" \"${DOCKER_CONTAINER_SPECPATH}\" && docker save \"${DOCKER_CONTAINER_NAME}\" | gzip -9 > \"${DOCKER_IMAGE_FILE}\" ) || true"
